In [60]:
import pandas as pd
import sklearn as sk
import numpy as np
from catboost import CatBoostRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import GradientBoostingRegressor

Firstly, we have to load the data

In [61]:
train_data = pd.read_csv('../data/train.csv')
test_data = pd.read_csv('../data/test.csv')

In [62]:
train_data.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [63]:
test_data.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty
0,630000,24,other,ba,6.85,65.2,yes,5.2,poor,group study,high,easy
1,630001,18,male,diploma,6.61,45.0,no,9.3,poor,coaching,low,easy
2,630002,24,female,b.tech,6.60,98.5,yes,6.2,good,group study,medium,moderate
3,630003,24,male,diploma,3.03,66.3,yes,5.7,average,mixed,medium,moderate
4,630004,20,female,b.tech,2.03,42.4,yes,9.2,average,coaching,low,moderate

The data seem pretty straightforward and they do not seem to need many modification, we could plot some graphs to get a better sense of the data as well as in the string values get the number of unique values. We do that because if we want to recreate that data as boolean columns, then it would not be beneficial if we had a huge number of columns. A lot of models do not accept or take way too long to train if the values in the columns are not numeric or boolean values.

In [64]:
unique_course_values = train_data['course'].unique()
unique_sleep_quality = train_data['sleep_quality'].unique()
unique_study_method = train_data['study_method'].unique()
unique_facility_rating = train_data['facility_rating'].unique()
unique_exam_difficulty = train_data['exam_difficulty'].unique()
print(f'Unique course values: {len(unique_course_values)}')
print(f'Unique sleep quality: {len(unique_sleep_quality)}')
print(f'Unique study method: {len(unique_study_method)}')
print(f'Unique facility rating: {len(unique_facility_rating)}')
print(f'Unique exam difficulty: {len(unique_facility_rating)}')

Unique course values: 7
Unique sleep quality: 3
Unique study method: 5
Unique facility rating: 3
Unique exam difficulty: 3

We can see that the number of unique values is not that high, so we could actually perform one hot encoding, something we should probably check is that we are not missing any unique values on the testing set that do not appear on the training one. Next we can view how many values are missing, so that we can take the correct approach to filling them, e.g with 0, median value, mean value etc

In [65]:
print(f'The na values for the training set:\n {train_data.isna().sum()}')
print(f'The na values for the testing set:\n {test_data.isna().sum()}')

The na values for the training set:
 id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64
The na values for the testing set:
 id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
dtype: int64

So there seem to be no missing values in the dataset, so we do not really have to fill any values, we will then go on to one hot encoding the feature columns.

In [66]:
feature_columns = train_data.select_dtypes(include=['object']).columns
train_data = pd.get_dummies(data=train_data, columns=feature_columns)
test_data = pd.get_dummies(data=test_data, columns=feature_columns)

In [67]:
train_data.head()

,id,age,study_hours,class_attendance,sleep_hours,exam_score,gender_female,gender_male,gender_other,course_b.com,...,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,facility_rating_high,facility_rating_low,facility_rating_medium,exam_difficulty_easy,exam_difficulty_hard,exam_difficulty_moderate
0,0,21,7.91,98.8,4.9,78.3,True,False,False,False,...,False,False,True,False,False,True,False,True,False,False
1,1,18,4.95,94.8,4.7,46.7,False,False,True,False,...,False,False,False,True,False,False,True,False,False,True
2,2,20,4.68,92.6,5.8,99.0,True,False,False,False,...,False,False,False,False,True,False,False,False,False,True
3,3,19,2.00,49.5,8.3,63.9,False,True,False,False,...,True,False,False,False,True,False,False,False,False,True
4,4,23,7.65,86.9,9.6,100.0,False,True,False,False,...,False,False,False,True,True,False,False,True,False,False

In [68]:
test_data.head()

,id,age,study_hours,class_attendance,sleep_hours,gender_female,gender_male,gender_other,course_b.com,course_b.sc,...,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,facility_rating_high,facility_rating_low,facility_rating_medium,exam_difficulty_easy,exam_difficulty_hard,exam_difficulty_moderate
0,630000,24,6.85,65.2,5.2,False,False,True,False,False,...,True,False,False,False,True,False,False,True,False,False
1,630001,18,6.61,45.0,9.3,False,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
2,630002,24,6.60,98.5,6.2,True,False,False,False,False,...,True,False,False,False,False,False,True,False,False,True
3,630003,24,3.03,66.3,5.7,False,True,False,False,False,...,False,True,False,False,False,False,True,False,False,True
4,630004,20,2.03,42.4,9.2,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True

So now we can try to use different models and get our predictions.

In [69]:
y_train = train_data['exam_score']
X_train = train_data.drop('exam_score', axis=1)
student_ids = test_data['id']
X_test = test_data

X_test.drop('id', axis=1)
X_train.drop('id', axis=1)

,age,study_hours,class_attendance,sleep_hours,gender_female,gender_male,gender_other,course_b.com,course_b.sc,course_b.tech,...,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,facility_rating_high,facility_rating_low,facility_rating_medium,exam_difficulty_easy,exam_difficulty_hard,exam_difficulty_moderate
0,21,7.91,98.8,4.9,True,False,False,False,True,False,...,False,False,True,False,False,True,False,True,False,False
1,18,4.95,94.8,4.7,False,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,True
2,20,4.68,92.6,5.8,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
3,19,2.00,49.5,8.3,False,True,False,False,True,False,...,True,False,False,False,True,False,False,False,False,True
4,23,7.65,86.9,9.6,False,True,False,False,False,False,...,False,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,18,4.86,70.7,4.1,True,False,False,False,False,True,...,False,True,False,False,True,False,False,False,False,True
629996,21,7.08,54.4,4.5,True,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,True
629997,24,0.64,44.2,4.3,False,True,False,False,False,False,...,False,False,True,False,False,True,False,False,False,True
629998,20,1.54,75.1,8.2,False,True,False,True,False,False,...,True,False,False,False,True,False,False,False,False,True
629999,18,3.94,75.3,5.8,False,False,True,False,False,True,...,False,False,True,False,False,True,False,True,False,False

Firstly, we can try to use the cat boost regressor.

In [70]:
model = CatBoostRegressor()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)

submission = pd.DataFrame({
    'id': student_ids,
    'exam_score': y_predict
})

submission.to_csv('../data/catboost_submission_final.csv', index=False)

Learning rate set to 0.113364
0:	learn: 17.5093259	total: 68.4ms	remaining: 1m 8s
1:	learn: 16.3056014	total: 120ms	remaining: 59.8s
2:	learn: 15.2867049	total: 176ms	remaining: 58.5s
3:	learn: 14.3852511	total: 228ms	remaining: 56.7s
4:	learn: 13.6043911	total: 291ms	remaining: 57.8s
5:	learn: 12.9252648	total: 347ms	remaining: 57.5s
6:	learn: 12.3495883	total: 407ms	remaining: 57.8s
7:	learn: 11.8647542	total: 457ms	remaining: 56.6s
8:	learn: 11.4544933	total: 506ms	remaining: 55.7s
9:	learn: 11.0973666	total: 563ms	remaining: 55.7s
10:	learn: 10.7933629	total: 612ms	remaining: 55s
11:	learn: 10.5301079	total: 658ms	remaining: 54.2s
12:	learn: 10.3077738	total: 709ms	remaining: 53.8s
13:	learn: 10.1175356	total: 761ms	remaining: 53.6s
14:	learn: 9.9499404	total: 815ms	remaining: 53.5s
15:	learn: 9.8064613	total: 872ms	remaining: 53.6s
16:	learn: 9.6847372	total: 930ms	remaining: 53.7s
17:	learn: 9.5773092	total: 988ms	remaining: 53.9s
18:	learn: 9.4865833	total: 1.04s	remaining: 53.6s
19:	learn: 9.4075581	total: 1.09s	remaining: 53.4s
20:	learn: 9.3400739	total: 1.14s	remaining: 53s
21:	learn: 9.2807470	total: 1.18s	remaining: 52.5s
22:	learn: 9.2292681	total: 1.22s	remaining: 52s
23:	learn: 9.1857529	total: 1.26s	remaining: 51.5s
24:	learn: 9.1473562	total: 1.3s	remaining: 50.9s
25:	learn: 9.1129189	total: 1.34s	remaining: 50.3s
26:	learn: 9.0833521	total: 1.39s	remaining: 50s
27:	learn: 9.0565677	total: 1.43s	remaining: 49.5s
28:	learn: 9.0346322	total: 1.47s	remaining: 49.1s
29:	learn: 9.0135287	total: 1.51s	remaining: 48.7s
30:	learn: 8.9954003	total: 1.54s	remaining: 48.3s
31:	learn: 8.9798125	total: 1.59s	remaining: 48.1s
32:	learn: 8.9658932	total: 1.63s	remaining: 47.7s
33:	learn: 8.9530209	total: 1.67s	remaining: 47.5s
34:	learn: 8.9422400	total: 1.73s	remaining: 47.6s
35:	learn: 8.9327446	total: 1.79s	remaining: 48s
36:	learn: 8.9234486	total: 1.85s	remaining: 48.2s
37:	learn: 8.9159898	total: 1.9s	remaining: 48.2s
38:	learn: 8.9088522	total: 1.95s	remaining: 48.1s
39:	learn: 8.9028204	total: 2s	remaining: 48s
40:	learn: 8.8973905	total: 2.05s	remaining: 48s
41:	learn: 8.8929297	total: 2.1s	remaining: 47.9s
42:	learn: 8.8885781	total: 2.14s	remaining: 47.7s
43:	learn: 8.8847855	total: 2.19s	remaining: 47.6s
44:	learn: 8.8816735	total: 2.23s	remaining: 47.4s
45:	learn: 8.8789753	total: 2.27s	remaining: 47.2s
46:	learn: 8.8761880	total: 2.31s	remaining: 46.9s
47:	learn: 8.8738825	total: 2.35s	remaining: 46.6s
48:	learn: 8.8717216	total: 2.39s	remaining: 46.4s
49:	learn: 8.8696250	total: 2.43s	remaining: 46.2s
50:	learn: 8.8677079	total: 2.47s	remaining: 46s
51:	learn: 8.8662434	total: 2.51s	remaining: 45.8s
52:	learn: 8.8647891	total: 2.56s	remaining: 45.7s
53:	learn: 8.8628467	total: 2.6s	remaining: 45.6s
54:	learn: 8.8613347	total: 2.64s	remaining: 45.3s
55:	learn: 8.8601148	total: 2.68s	remaining: 45.2s
56:	learn: 8.8591244	total: 2.72s	remaining: 45s
57:	learn: 8.8580909	total: 2.76s	remaining: 44.8s
58:	learn: 8.8570903	total: 2.79s	remaining: 44.6s
59:	learn: 8.8563080	total: 2.83s	remaining: 44.4s
60:	learn: 8.8552545	total: 2.88s	remaining: 44.3s
61:	learn: 8.8545386	total: 2.91s	remaining: 44.1s
62:	learn: 8.8538789	total: 2.95s	remaining: 43.9s
63:	learn: 8.8533326	total: 2.99s	remaining: 43.7s
64:	learn: 8.8526572	total: 3.03s	remaining: 43.6s
65:	learn: 8.8519950	total: 3.08s	remaining: 43.5s
66:	learn: 8.8511343	total: 3.12s	remaining: 43.4s
67:	learn: 8.8505383	total: 3.16s	remaining: 43.3s
68:	learn: 8.8500326	total: 3.2s	remaining: 43.2s
69:	learn: 8.8494587	total: 3.25s	remaining: 43.2s
70:	learn: 8.8485677	total: 3.3s	remaining: 43.2s
71:	learn: 8.8484075	total: 3.35s	remaining: 43.1s
72:	learn: 8.8479389	total: 3.39s	remaining: 43s
73:	learn: 8.8473936	total: 3.44s	remaining: 43s
74:	learn: 8.8469543	total: 3.48s	remaining: 42.9s
75:	learn: 8.8460710	total: 3.52s	remaining: 42.8s
76:	learn: 8.8452249	total: 3.57s	remaining: 42.8s
77:	learn: 8.8446893	total: 3.62s	remaining: 42.8s
78:	learn: 8.8439864	total: 3.67s	remaining: 42.8s
79:	learn: 8.8433378	total: 3.72s	remaining: 42.8s
80:	learn: 8.8428532	total: 3.76s	remaining: 42.7s
81:	learn: 8.8421877	total: 3.81s	remaining: 42.6s
82:	learn: 8.8416158	total: 3.85s	remaining: 42.5s
83:	learn: 8.8413652	total: 3.89s	remaining: 42.4s
84:	learn: 8.8404602	total: 3.93s	remaining: 42.3s
85:	learn: 8.8398138	total: 3.97s	remaining: 42.2s
86:	learn: 8.8393500	total: 4s	remaining: 42s
87:	learn: 8.8387898	total: 4.04s	remaining: 41.9s
88:	learn: 8.8384221	total: 4.08s	remaining: 41.8s
89:	learn: 8.8381585	total: 4.12s	remaining: 41.7s
90:	learn: 8.8377333	total: 4.16s	remaining: 41.6s
91:	learn: 8.8372260	total: 4.2s	remaining: 41.5s
92:	learn: 8.8367315	total: 4.24s	remaining: 41.3s
93:	learn: 8.8365269	total: 4.28s	remaining: 41.2s
94:	learn: 8.8361214	total: 4.32s	remaining: 41.2s
95:	learn: 8.8355507	total: 4.37s	remaining: 41.1s
96:	learn: 8.8352523	total: 4.4s	remaining: 41s
97:	learn: 8.8347756	total: 4.44s	remaining: 40.9s
98:	learn: 8.8344774	total: 4.48s	remaining: 40.8s
99:	learn: 8.8340281	total: 4.52s	remaining: 40.7s
100:	learn: 8.8335925	total: 4.56s	remaining: 40.6s
101:	learn: 8.8332042	total: 4.6s	remaining: 40.5s
102:	learn: 8.8326442	total: 4.64s	remaining: 40.4s
103:	learn: 8.8321430	total: 4.69s	remaining: 40.4s
104:	learn: 8.8314029	total: 4.74s	remaining: 40.4s
105:	learn: 8.8309069	total: 4.8s	remaining: 40.5s
106:	learn: 8.8305332	total: 4.85s	remaining: 40.5s
107:	learn: 8.8299547	total: 4.91s	remaining: 40.5s
108:	learn: 8.8294488	total: 4.95s	remaining: 40.5s
109:	learn: 8.8291510	total: 5s	remaining: 40.5s
110:	learn: 8.8289600	total: 5.04s	remaining: 40.4s
111:	learn: 8.8285788	total: 5.09s	remaining: 40.4s
112:	learn: 8.8282417	total: 5.14s	remaining: 40.4s
113:	learn: 8.8279810	total: 5.19s	remaining: 40.4s
114:	learn: 8.8276453	total: 5.24s	remaining: 40.3s
115:	learn: 8.8273801	total: 5.28s	remaining: 40.3s
116:	learn: 8.8269442	total: 5.33s	remaining: 40.2s
117:	learn: 8.8266445	total: 5.37s	remaining: 40.1s
118:	learn: 8.8262520	total: 5.41s	remaining: 40s
119:	learn: 8.8256266	total: 5.45s	remaining: 39.9s
120:	learn: 8.8252816	total: 5.48s	remaining: 39.8s
121:	learn: 8.8248730	total: 5.53s	remaining: 39.8s
122:	learn: 8.8245310	total: 5.57s	remaining: 39.7s
123:	learn: 8.8240307	total: 5.62s	remaining: 39.7s
124:	learn: 8.8235458	total: 5.66s	remaining: 39.6s
125:	learn: 8.8233040	total: 5.7s	remaining: 39.6s
126:	learn: 8.8229905	total: 5.74s	remaining: 39.5s
127:	learn: 8.8226641	total: 5.78s	remaining: 39.4s
128:	learn: 8.8221724	total: 5.82s	remaining: 39.3s
129:	learn: 8.8217098	total: 5.86s	remaining: 39.2s
130:	learn: 8.8212388	total: 5.9s	remaining: 39.2s
131:	learn: 8.8207466	total: 5.94s	remaining: 39.1s
132:	learn: 8.8204451	total: 5.98s	remaining: 39s
133:	learn: 8.8199062	total: 6.02s	remaining: 38.9s
134:	learn: 8.8192902	total: 6.06s	remaining: 38.8s
135:	learn: 8.8188943	total: 6.11s	remaining: 38.8s
136:	learn: 8.8184335	total: 6.15s	remaining: 38.7s
137:	learn: 8.8180283	total: 6.19s	remaining: 38.7s
138:	learn: 8.8174188	total: 6.24s	remaining: 38.7s
139:	learn: 8.8170495	total: 6.29s	remaining: 38.7s
140:	learn: 8.8166918	total: 6.34s	remaining: 38.6s
141:	learn: 8.8163745	total: 6.4s	remaining: 38.7s
142:	learn: 8.8160678	total: 6.44s	remaining: 38.6s
143:	learn: 8.8157379	total: 6.49s	remaining: 38.6s
144:	learn: 8.8151632	total: 6.54s	remaining: 38.5s
145:	learn: 8.8147924	total: 6.58s	remaining: 38.5s
146:	learn: 8.8144120	total: 6.63s	remaining: 38.5s
147:	learn: 8.8140342	total: 6.67s	remaining: 38.4s
148:	learn: 8.8137475	total: 6.72s	remaining: 38.4s
149:	learn: 8.8133769	total: 6.76s	remaining: 38.3s
150:	learn: 8.8130371	total: 6.8s	remaining: 38.3s
151:	learn: 8.8127324	total: 6.84s	remaining: 38.1s
152:	learn: 8.8123318	total: 6.88s	remaining: 38.1s
153:	learn: 8.8119791	total: 6.92s	remaining: 38s
154:	learn: 8.8117618	total: 6.96s	remaining: 37.9s
155:	learn: 8.8114632	total: 7s	remaining: 37.9s
156:	learn: 8.8110789	total: 7.04s	remaining: 37.8s
157:	learn: 8.8108381	total: 7.08s	remaining: 37.7s
158:	learn: 8.8105158	total: 7.12s	remaining: 37.6s
159:	learn: 8.8101763	total: 7.16s	remaining: 37.6s
160:	learn: 8.8099021	total: 7.2s	remaining: 37.5s
161:	learn: 8.8095718	total: 7.24s	remaining: 37.5s
162:	learn: 8.8093278	total: 7.28s	remaining: 37.4s
163:	learn: 8.8089967	total: 7.32s	remaining: 37.3s
164:	learn: 8.8085853	total: 7.36s	remaining: 37.3s
165:	learn: 8.8083551	total: 7.41s	remaining: 37.2s
166:	learn: 8.8080411	total: 7.44s	remaining: 37.1s
167:	learn: 8.8077008	total: 7.49s	remaining: 37.1s
168:	learn: 8.8074080	total: 7.53s	remaining: 37s
169:	learn: 8.8070614	total: 7.57s	remaining: 37s
170:	learn: 8.8067247	total: 7.62s	remaining: 36.9s
171:	learn: 8.8064312	total: 7.67s	remaining: 36.9s
172:	learn: 8.8062468	total: 7.71s	remaining: 36.8s
173:	learn: 8.8059152	total: 7.75s	remaining: 36.8s
174:	learn: 8.8056272	total: 7.8s	remaining: 36.8s
175:	learn: 8.8052450	total: 7.86s	remaining: 36.8s
176:	learn: 8.8050684	total: 7.94s	remaining: 36.9s
177:	learn: 8.8046690	total: 8.02s	remaining: 37s
178:	learn: 8.8044038	total: 8.07s	remaining: 37s
179:	learn: 8.8041610	total: 8.14s	remaining: 37.1s
180:	learn: 8.8038884	total: 8.2s	remaining: 37.1s
181:	learn: 8.8034709	total: 8.27s	remaining: 37.1s
182:	learn: 8.8033369	total: 8.33s	remaining: 37.2s
183:	learn: 8.8031021	total: 8.4s	remaining: 37.2s
184:	learn: 8.8027605	total: 8.46s	remaining: 37.3s
185:	learn: 8.8025140	total: 8.51s	remaining: 37.2s
186:	learn: 8.8023219	total: 8.56s	remaining: 37.2s
187:	learn: 8.8019592	total: 8.63s	remaining: 37.3s
188:	learn: 8.8015970	total: 8.7s	remaining: 37.3s
189:	learn: 8.8013213	total: 8.76s	remaining: 37.4s
190:	learn: 8.8011035	total: 8.81s	remaining: 37.3s
191:	learn: 8.8008052	total: 8.87s	remaining: 37.3s
192:	learn: 8.8006249	total: 8.92s	remaining: 37.3s
193:	learn: 8.8004142	total: 8.97s	remaining: 37.3s
194:	learn: 8.8001555	total: 9.02s	remaining: 37.2s
195:	learn: 8.7997579	total: 9.08s	remaining: 37.2s
196:	learn: 8.7992617	total: 9.13s	remaining: 37.2s
197:	learn: 8.7990197	total: 9.19s	remaining: 37.2s
198:	learn: 8.7987559	total: 9.25s	remaining: 37.2s
199:	learn: 8.7984513	total: 9.31s	remaining: 37.2s
200:	learn: 8.7982480	total: 9.41s	remaining: 37.4s
201:	learn: 8.7980396	total: 9.54s	remaining: 37.7s
202:	learn: 8.7976021	total: 9.69s	remaining: 38s
203:	learn: 8.7973625	total: 9.83s	remaining: 38.4s
204:	learn: 8.7971788	total: 9.97s	remaining: 38.7s
205:	learn: 8.7970013	total: 10.2s	remaining: 39.3s
206:	learn: 8.7966846	total: 10.4s	remaining: 39.7s
207:	learn: 8.7964438	total: 10.5s	remaining: 40.1s
208:	learn: 8.7961901	total: 10.7s	remaining: 40.4s
209:	learn: 8.7958978	total: 10.9s	remaining: 40.9s
210:	learn: 8.7956738	total: 11s	remaining: 41.2s
211:	learn: 8.7954074	total: 11.2s	remaining: 41.5s
212:	learn: 8.7951812	total: 11.3s	remaining: 41.8s
213:	learn: 8.7949018	total: 11.5s	remaining: 42.1s
214:	learn: 8.7947216	total: 11.6s	remaining: 42.4s
215:	learn: 8.7945139	total: 11.7s	remaining: 42.5s
216:	learn: 8.7943292	total: 11.8s	remaining: 42.6s
217:	learn: 8.7940675	total: 11.9s	remaining: 42.7s
218:	learn: 8.7937319	total: 12s	remaining: 42.9s
219:	learn: 8.7934930	total: 12.1s	remaining: 43s
220:	learn: 8.7932857	total: 12.3s	remaining: 43.2s
221:	learn: 8.7930620	total: 12.3s	remaining: 43.3s
222:	learn: 8.7927527	total: 12.5s	remaining: 43.4s
223:	learn: 8.7924706	total: 12.6s	remaining: 43.6s
224:	learn: 8.7921618	total: 12.7s	remaining: 43.7s
225:	learn: 8.7920015	total: 12.8s	remaining: 43.8s
226:	learn: 8.7918328	total: 12.9s	remaining: 43.8s
227:	learn: 8.7915999	total: 13s	remaining: 43.9s
228:	learn: 8.7914210	total: 13.1s	remaining: 44s
229:	learn: 8.7911269	total: 13.2s	remaining: 44s
230:	learn: 8.7908323	total: 13.2s	remaining: 44.1s
231:	learn: 8.7905314	total: 13.3s	remaining: 44.1s
232:	learn: 8.7902646	total: 13.4s	remaining: 44.2s
233:	learn: 8.7900747	total: 13.5s	remaining: 44.2s
234:	learn: 8.7898076	total: 13.6s	remaining: 44.3s
235:	learn: 8.7895759	total: 13.7s	remaining: 44.3s
236:	learn: 8.7892517	total: 13.8s	remaining: 44.4s
237:	learn: 8.7889128	total: 13.9s	remaining: 44.4s
238:	learn: 8.7887310	total: 14s	remaining: 44.4s
239:	learn: 8.7885739	total: 14s	remaining: 44.5s
240:	learn: 8.7884013	total: 14.1s	remaining: 44.5s
241:	learn: 8.7880719	total: 14.2s	remaining: 44.6s
242:	learn: 8.7878588	total: 14.3s	remaining: 44.6s
243:	learn: 8.7874931	total: 14.4s	remaining: 44.6s
244:	learn: 8.7872002	total: 14.5s	remaining: 44.7s
245:	learn: 8.7870132	total: 14.7s	remaining: 45s
246:	learn: 8.7868121	total: 14.9s	remaining: 45.4s
247:	learn: 8.7865547	total: 15s	remaining: 45.6s
248:	learn: 8.7863225	total: 15.2s	remaining: 46s
249:	learn: 8.7861253	total: 15.4s	remaining: 46.3s
250:	learn: 8.7859269	total: 15.6s	remaining: 46.5s
251:	learn: 8.7857603	total: 15.9s	remaining: 47.3s
252:	learn: 8.7855359	total: 16.2s	remaining: 47.9s
253:	learn: 8.7852788	total: 16.4s	remaining: 48.3s
254:	learn: 8.7849909	total: 16.6s	remaining: 48.5s
255:	learn: 8.7847960	total: 16.8s	remaining: 48.9s
256:	learn: 8.7845754	total: 17s	remaining: 49.1s
257:	learn: 8.7842132	total: 17.2s	remaining: 49.4s
258:	learn: 8.7838944	total: 17.3s	remaining: 49.5s
259:	learn: 8.7837215	total: 17.4s	remaining: 49.5s
260:	learn: 8.7834400	total: 17.5s	remaining: 49.7s
261:	learn: 8.7832201	total: 17.7s	remaining: 50s
262:	learn: 8.7829887	total: 18s	remaining: 50.3s
263:	learn: 8.7826507	total: 18.1s	remaining: 50.4s
264:	learn: 8.7824759	total: 18.2s	remaining: 50.6s
265:	learn: 8.7822814	total: 18.4s	remaining: 50.8s
266:	learn: 8.7821520	total: 18.6s	remaining: 51.2s
267:	learn: 8.7819669	total: 18.8s	remaining: 51.4s
268:	learn: 8.7815164	total: 19s	remaining: 51.6s
269:	learn: 8.7813686	total: 19.1s	remaining: 51.7s
270:	learn: 8.7811099	total: 19.2s	remaining: 51.7s
271:	learn: 8.7808003	total: 19.3s	remaining: 51.7s
272:	learn: 8.7806507	total: 19.5s	remaining: 51.8s
273:	learn: 8.7804577	total: 19.6s	remaining: 51.8s
274:	learn: 8.7802353	total: 19.7s	remaining: 51.8s
275:	learn: 8.7800634	total: 19.8s	remaining: 52s
276:	learn: 8.7798599	total: 20.1s	remaining: 52.4s
277:	learn: 8.7795789	total: 20.2s	remaining: 52.4s
278:	learn: 8.7793412	total: 20.3s	remaining: 52.4s
279:	learn: 8.7790106	total: 20.4s	remaining: 52.5s
280:	learn: 8.7787608	total: 20.5s	remaining: 52.5s
281:	learn: 8.7785885	total: 20.6s	remaining: 52.5s
282:	learn: 8.7783951	total: 20.7s	remaining: 52.5s
283:	learn: 8.7782501	total: 20.8s	remaining: 52.5s
284:	learn: 8.7780621	total: 20.9s	remaining: 52.5s
285:	learn: 8.7779347	total: 21s	remaining: 52.5s
286:	learn: 8.7777655	total: 21.1s	remaining: 52.4s
287:	learn: 8.7775654	total: 21.2s	remaining: 52.4s
288:	learn: 8.7773503	total: 21.3s	remaining: 52.4s
289:	learn: 8.7771621	total: 21.4s	remaining: 52.4s
290:	learn: 8.7769451	total: 21.5s	remaining: 52.4s
291:	learn: 8.7767774	total: 21.6s	remaining: 52.3s
292:	learn: 8.7766371	total: 21.7s	remaining: 52.3s
293:	learn: 8.7763824	total: 21.8s	remaining: 52.2s
294:	learn: 8.7761742	total: 21.9s	remaining: 52.2s
295:	learn: 8.7759674	total: 21.9s	remaining: 52.2s
296:	learn: 8.7758197	total: 22s	remaining: 52.1s
297:	learn: 8.7756922	total: 22.1s	remaining: 52.1s
298:	learn: 8.7754636	total: 22.2s	remaining: 52.1s
299:	learn: 8.7752978	total: 22.3s	remaining: 52.1s
300:	learn: 8.7751653	total: 22.4s	remaining: 52.1s
301:	learn: 8.7748560	total: 22.5s	remaining: 52.1s
302:	learn: 8.7747246	total: 22.6s	remaining: 52s
303:	learn: 8.7745664	total: 22.7s	remaining: 51.9s
304:	learn: 8.7743121	total: 22.8s	remaining: 51.9s
305:	learn: 8.7739785	total: 22.9s	remaining: 51.9s
306:	learn: 8.7737829	total: 23s	remaining: 51.8s
307:	learn: 8.7735985	total: 23.1s	remaining: 51.8s
308:	learn: 8.7733377	total: 23.1s	remaining: 51.8s
309:	learn: 8.7731449	total: 23.2s	remaining: 51.7s
310:	learn: 8.7727311	total: 23.3s	remaining: 51.7s
311:	learn: 8.7725629	total: 23.4s	remaining: 51.7s
312:	learn: 8.7723621	total: 23.5s	remaining: 51.7s
313:	learn: 8.7722105	total: 23.6s	remaining: 51.7s
314:	learn: 8.7719609	total: 23.7s	remaining: 51.6s
315:	learn: 8.7717006	total: 23.8s	remaining: 51.6s
316:	learn: 8.7715022	total: 23.9s	remaining: 51.5s
317:	learn: 8.7711808	total: 24s	remaining: 51.5s
318:	learn: 8.7709745	total: 24.1s	remaining: 51.5s
319:	learn: 8.7708639	total: 24.2s	remaining: 51.5s
320:	learn: 8.7706396	total: 24.4s	remaining: 51.5s
321:	learn: 8.7704111	total: 24.5s	remaining: 51.6s
322:	learn: 8.7701917	total: 24.6s	remaining: 51.5s
323:	learn: 8.7699639	total: 24.7s	remaining: 51.5s
324:	learn: 8.7697467	total: 24.8s	remaining: 51.5s
325:	learn: 8.7695848	total: 25s	remaining: 51.6s
326:	learn: 8.7694637	total: 25.1s	remaining: 51.7s
327:	learn: 8.7692784	total: 25.2s	remaining: 51.7s
328:	learn: 8.7691342	total: 25.4s	remaining: 51.7s
329:	learn: 8.7690270	total: 25.5s	remaining: 51.7s
330:	learn: 8.7688744	total: 25.6s	remaining: 51.8s
331:	learn: 8.7687138	total: 25.7s	remaining: 51.8s
332:	learn: 8.7685678	total: 25.8s	remaining: 51.7s
333:	learn: 8.7684396	total: 25.9s	remaining: 51.7s
334:	learn: 8.7681920	total: 26s	remaining: 51.6s
335:	learn: 8.7679824	total: 26.1s	remaining: 51.5s
336:	learn: 8.7677530	total: 26.2s	remaining: 51.5s
337:	learn: 8.7675723	total: 26.3s	remaining: 51.5s
338:	learn: 8.7673303	total: 26.4s	remaining: 51.6s
339:	learn: 8.7671729	total: 26.6s	remaining: 51.5s
340:	learn: 8.7670306	total: 26.7s	remaining: 51.5s
341:	learn: 8.7668325	total: 26.8s	remaining: 51.5s
342:	learn: 8.7666743	total: 26.9s	remaining: 51.5s
343:	learn: 8.7663978	total: 27s	remaining: 51.5s
344:	learn: 8.7661377	total: 27.1s	remaining: 51.4s
345:	learn: 8.7660133	total: 27.2s	remaining: 51.4s
346:	learn: 8.7658255	total: 27.3s	remaining: 51.4s
347:	learn: 8.7655748	total: 27.4s	remaining: 51.4s
348:	learn: 8.7653556	total: 27.5s	remaining: 51.4s
349:	learn: 8.7652258	total: 27.6s	remaining: 51.3s
350:	learn: 8.7650732	total: 27.7s	remaining: 51.3s
351:	learn: 8.7649083	total: 27.8s	remaining: 51.2s
352:	learn: 8.7646955	total: 27.9s	remaining: 51.2s
353:	learn: 8.7645046	total: 28s	remaining: 51.1s
354:	learn: 8.7643084	total: 28.1s	remaining: 51.1s
355:	learn: 8.7640969	total: 28.2s	remaining: 51.1s
356:	learn: 8.7639331	total: 28.3s	remaining: 51s
357:	learn: 8.7637978	total: 28.4s	remaining: 51s
358:	learn: 8.7636156	total: 28.5s	remaining: 51s
359:	learn: 8.7634265	total: 28.7s	remaining: 50.9s
360:	learn: 8.7632455	total: 28.8s	remaining: 50.9s
361:	learn: 8.7631231	total: 28.9s	remaining: 50.9s
362:	learn: 8.7629738	total: 29s	remaining: 50.9s
363:	learn: 8.7627948	total: 29.1s	remaining: 50.9s
364:	learn: 8.7626325	total: 29.2s	remaining: 50.8s
365:	learn: 8.7624805	total: 29.3s	remaining: 50.8s
366:	learn: 8.7622795	total: 29.4s	remaining: 50.7s
367:	learn: 8.7621100	total: 29.5s	remaining: 50.7s
368:	learn: 8.7619811	total: 29.6s	remaining: 50.6s
369:	learn: 8.7618786	total: 29.7s	remaining: 50.6s
370:	learn: 8.7617532	total: 29.8s	remaining: 50.5s
371:	learn: 8.7613993	total: 29.9s	remaining: 50.4s
372:	learn: 8.7612715	total: 29.9s	remaining: 50.3s
373:	learn: 8.7610826	total: 30s	remaining: 50.3s
374:	learn: 8.7608825	total: 30.1s	remaining: 50.2s
375:	learn: 8.7606943	total: 30.2s	remaining: 50.2s
376:	learn: 8.7603998	total: 30.3s	remaining: 50.1s
377:	learn: 8.7602614	total: 30.4s	remaining: 50.1s
378:	learn: 8.7600399	total: 30.6s	remaining: 50.1s
379:	learn: 8.7597468	total: 30.7s	remaining: 50s
380:	learn: 8.7595290	total: 30.8s	remaining: 50s
381:	learn: 8.7593504	total: 30.9s	remaining: 50s
382:	learn: 8.7592382	total: 31s	remaining: 50s
383:	learn: 8.7591230	total: 31.2s	remaining: 50s
384:	learn: 8.7589604	total: 31.2s	remaining: 49.9s
385:	learn: 8.7587538	total: 31.4s	remaining: 49.9s
386:	learn: 8.7586143	total: 31.5s	remaining: 49.9s
387:	learn: 8.7584661	total: 31.6s	remaining: 49.9s

Then, we can go on by trying out stacking, the cat boost is pretty good with these types of problems, but by using stacking and letting a lot of different models help predict the final output the results will probably improve

In [ ]:

base_models = {
    'xgboost': xgb.XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42),
    'lightgbm': lgb.LGBMRegressor(n_estimators=300, learning_rate=0.05, random_state=42, verbose=-1),
    'catboost': CatBoostRegressor(iterations=300, verbose=False, random_state=42),
    # 'rf': sk.ensemble.RandomForestRegressor(n_estimators=300, random_state=42),
    # 'extra_trees': sk.ensemble.ExtraTreesRegressor(n_estimators=200, random_state=42),
    'gradient_boost': GradientBoostingRegressor(n_estimators=200, random_state=42),
    'logistic': sk.linear_model.LogisticRegression(max_iter=5000, random_state=42),
    'naive_bayes': sk.naive_bayes.GaussianNB()
}

Kfold = sk.model_selection.KFold(n_splits=5, shuffle=True, random_state=42)

layer1_predictions = np.zeros((len(X_train), len(base_models)))

for fold_idx, (train_idx, test_idx) in enumerate(Kfold.split(X_train)):
    X_fold_train, X_fold_val = X_train.iloc[train_idx], X_train.iloc[test_idx]
    y_fold_train, y_fold_val = y_train[train_idx], y_train[test_idx]

    for model_idx, (name, model) in enumerate(base_models.items()):
        model.fit(X_fold_train, y_fold_train)
        if hasattr(model, 'predict_proba'):
            predictions = model.predict_proba(X_fold_val)[:, 1]
        else:
            predictions = model.predict(X_fold_val)

        layer1_predictions[test_idx, model_idx] = predictions

meta_model = sk.LogisticRegression(max_iter=5000, random_state=42)
meta_model.fit(layer1_predictions, y_train)

for name, model in base_models.items():
    model.fit(X_train, y_train)

layer1_test_predictions = np.zeros((len(X_train), len(base_models)))

for model_idx, (name, model) in enumerate(base_models.items()):
    if hasattr(model, 'predict_proba'):
        layer1_test_predictions[:, model_idx] = model.predict_proba(X_test)[:, 1]
    else:
        layer1_test_predictions[:, model_idx] = model.predict(X_test)

final_prediction = meta_model.predict(layer1_test_predictions)
print(final_prediction)

submission = pd.DataFrame({
    'id': student_ids,
    'exam_score': final_prediction
})
submission.to_csv('../data/StackedPredictions.csv', index=False)
print("\n✓ Submission saved!")
print(submission.head())